version: "2.4"
services:
  postgresql:
    build:
      context: .
      dockerfile: postgresql
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    build:
      context: .
      dockerfile: pgadmin
    container_name: pgadmin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-user-area:/var/lib/pgadmin
      - pgadmin-connection-info:/pgadmin4
    ports:
      - "80:80"
volumes:
  postgres-data:
  pgadmin-user-area:
  pgadmin-connection-info: